@startuml

//Caso a1

:Actor: as a1
:Actor\n: as a2



Rectangle Sistema{
a1 -> (Caso de uso)
a1 --> (Caso de uso\n)
a1 -> (Caso de uso\n\n)
a2 --> (Caso de uso)
a2 --> (Caso de uso\n\n)
}

note "comunicacion" as n1
note "Entorno del sistema" as n2

n1 --> Sistema
n2 --> Sistema

//Caso Biblioteca

:Socio: as s1
:Bibliotecario: as b1

rectangle Biblioteca{
(Reservar libro) as r1
(Prestar libro) as p1
(Devolver libro) as dev1
(Actualizar catálogo) as act1

s1 --> r1
s1 --> p1
s1 -> dev1
b1 --> p1
b1 -> act1
}

// Caso Inclusión



:Bibliotecario: as b1

b1 -> (Baja socio)

(Baja socio) ..> (Buscar socio) : <<include>>

//Caso Extension



:Agente: as a1

(evaluar solicitud de Crédito) as n1

a1 <- n1

(solicitar información adicional al cliente) as n2

n1 <.. n2 : <<extend>>

//Herencia



:Agente: as a1

(enviar solicitud crédito) as sol1
(enviar solicitud de crédito personal) as sol2
(enviar solicitud de crédto empresarial) as sol3

a1 -> sol1

sol1 <|-- sol2
sol1 <|-- sol3

//Herencia2

:Cliente Bancario: as c1
:Cliente corporativo: as c2
:Cliente Normal: as c3

note "Actor antecesor" as not1
note "Actor descendiente" as not2

not1 -> c1
not2 <- c3

c1 <|-- c2
c1 <|-- c3

//Diagrama Inicial
@startuml

left to right direction
:Empleado: as e1
:Administrador: as a1
Rectangle Empresa\nPedidos{
(Introducir pedido) as et1
(Cancelar pedido) as et2
(Obtener estado pedido) as et3
(Borrar pedido) as et4
(Buscar pedidos) as et5
(Alta cliente) as et6
(Buscar cliente) as et7
(Nuevo producto) as et8
(Borrar producto) as et9
e1 --> et1
e1 --> et2
e1 --> et3
e1 --> et4
e1 --> et5
e1 --> et6
e1 --> et7
a1 -left-> et8
a1 -left-> et9
}

//Diagrama estructurado

@startuml

left to right direction
:Empleado: as e1
(Alta Cliente) as et1
(Introducir pedido) as et2
(Obtener estado pedido) as et3
(Cancelar pedido) as et4
(Buscar pedido) as et7
e1 -right-> et1
e1 -right-> et2
e1 -right-> et3
e1 -right-> et4
e1 -right-> et7
(Buscar cliente) as et5
(Pago en cuenta) as et6

(Pago con tarjeta) as et8
et1 ..> et2 : extiende
et5 <.. et2 : incluye
et3 ..> et7 : incluye
et4 ..> et7 : incluye
et6 ..> et2 : extiende
et8 ..> et2 : extiende
@enduml